name: ai_hub
description: Hybrid Online/Offline AI Chat App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # HTTP requests
  http: ^1.2.0
  # Local storage
  shared_preferences: ^2.2.2
  # Internet connectivity check
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.3
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4
  flutter_markdown: ^0.7.3
  # UUID for message IDs
  uuid: ^4.3.3
  # Smooth animations
  flutter_animate: ^4.5.0
  # Icons
  cupertino_icons: ^1.0.6
  flutter_dotenv: ^5.1.0
  dio: ^5.4.0
  # File & image picking
  file_picker: ^6.1.1
  image_picker: ^1.0.7
  # Share content
  share_plus: ^7.2.2
  # Open URLs
  url_launcher: ^6.2.5
  syncfusion_flutter_pdf: ^29.1.38
  archive: ^4.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
